FROM ruby:2.5.1-alpine

RUN apk add --no-cache --update build-base \
    && rm -rf /var/cache/apk/*

ENV APP_HOME /app

RUN mkdir $APP_HOME

WORKDIR $APP_HOME
ADD Gemfile* $APP_HOME/
RUN gem install bundler --no-ri --no-rdoc &&  bundle install
ADD . $APP_HOME

ENV POST_SERVICE_HOST post
ENV POST_SERVICE_PORT 5000
ENV COMMENT_SERVICE_HOST comment
ENV COMMENT_SERVICE_PORT 9292

CMD ["puma"]
