global:
  slack_api_url: 'https://hooks.slack.com/services/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'
  route:
    receiver: 'slack-notifications'
  receivers:
  - name: 'slack-notifications'
    slack_configs:
    - channel: '#artem_brykin'
