FROM alpine:3.10
RUN apk add --no-cache python3 \
    && apk add build-base python3-dev  \
    && python3 -m ensurepip \
    && rm -r /usr/lib/python*/ensurepip \
    && pip3 install --no-cache --upgrade pip setuptools wheel \
    && ln -sf /usr/bin/python3 /usr/bin/python \
    && ln -sf pip3 /usr/bin/pip \
    && pip install cython \
    && rm -rf /var/cache/apk/*

WORKDIR /app
ADD . /app

RUN pip install -r /app/requirements.txt && rm -rf /root/.cache/*

ENV POST_DATABASE_HOST post_db
ENV POST_DATABASE posts

ENTRYPOINT ["python3", "post_app.py"]
