{
 "title": "Ui_Service_monitoring",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Env",
    "query": "label_values(kubernetes_namespace)"
   }
  ]
 },
 "panels": [
  {
   "title": "UI HTTP REQUESTS WITH ERRORS",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(ui_request_count{http_status=~\"^[45].*\"}[1m])"
    }
   ]
  },
  {
   "title": "95 PERCENTILE",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(ui_request_response_time_bucket[5m])) by (le))"
    }
   ]
  },
  {
   "title": "UI HTTP REQUESTS",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(ui_request_count{http_status=~\"^[23].*\",kubernetes_namespace=~\"$namespace\"}[1m])"
    },
    {}
   ]
  }
 ]
}